    <div class="row">
        <div class="col-md-9 col-md-push-3 orgClass">.col-md-9 .col-md-push-3</div>
        <div class="col-md-3 col-md-pull-9 orgClass">
            <?php
            if(isset($menusName)) {
                foreach ($menusName as $nameOrg) {
                    echo "<u>".$nameOrg->getMenuName()."</u>";
                }
            }
            ?>
            <hr>

            <?php
                foreach($dataContact as $orgName){
                    $orgNameArr[] = "{text:'".$orgName->getMcontactName()."'},";
                }
            $jsonEncodeOrgName = json_encode($orgNameArr);

            ?>
        </div>
    </div>
    <?php  echo "<pre>";print_r($orgNameArr);echo "</pre>"; ?>
    <div id="tree"></div>

  <script>

      var treeOrg = [
          <?php
            foreach ($orgNameArr as $test){
                echo $test;
            }
          ?>
      ];

      var tree = [
          {
              text: "Parent 1",
              nodes: [
                  {
                      text: "Child 1",
                      nodes: [
                          {
                              text: "Grandchild 1"
                          },
                          {
                              text: "Grandchild 2"
                          }
                      ]
                  },
                  {
                      text: "Child 2"
                  }
              ]
          },
          {
              text: "Parent 2"
          },
          {
              text: "Parent 3"
          },
          {
              text: "Parent 4"
          },
          {
              text: "Parent 5"
          }
      ];

      $('#tree').treeview({
          data: treeOrg,         // data is not optional
          levels: 5

      });
      </script>