<?php echo $this->getContent(); ?>
<div class="row">
    <div class="col s12">
        <ul class="tabs">
            <li class="tab col s3"><a href="#test1">Библиотеки</a></li>
            <li class="tab col s3"><a class="active" href="#test2">КДУ</a></li>
            <li class="tab col s3"><a href="#test3">Музеи</a></li>
            <li class="tab col s3"><a href="#test4">ДОД</a></li>
            <li class="tab col s3"><a href="#test5">ТЗО</a></li>
        </ul>
    </div>
    <div id="test1" class="col s12">

        <?php

        foreach($typecontact as $typecontactTel){
            print_r($typecontactTel);
            echo "<tr><td class='mdl-data-table__cell--non-numeric'><a href=".$_SERVER['REDIRECT_URL']."/extra/".$typecontactTel->getIdMtypecontact().">"
                .$typecontactTel->getMtypecontactBible().
                "</a></td></tr>";
        }
        ?>

    </div>
    <div id="test2" class="col s12">Test 2</div>
    <div id="test3" class="col s12">Test 3</div>
    <div id="test4" class="col s12">Test 4</div>
    <div id="test5" class="col s12">Test 4</div>
</div>