<?php //echo $_POST['id'];

foreach($typecontact as $valTypecontact){
    echo $valTypecontact->getMtypecontactBible();
}
//echo $typecontact->getMtypecontactBible();


?>

<div  ng-app="clientsApp" ng-controller="ClientsCtrl">
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Age</th>
            <th>Percentage</th>
        </tr>
        </thead>
        <tbody>
        <tr ng-repeat="client in clients">
            <td>{{ client.id }}</td>
            <td>{{ client.name }}</td>
            <td>{{ client.age }}</td>
            <td>{{ client.percentage }}</td>
        </tr>
        </tbody>
    </table>
</div>
