<?php

// $this->assets->outputJs();
echo \Phalcon\Tag::stylesheetLink("../phalcon/css/style.css");
echo \Phalcon\Tag::stylesheetLink("https://fonts.googleapis.com/icon?family=Material+Icons");
echo \Phalcon\Tag::stylesheetLink("https://code.getmdl.io/1.3.0/material.indigo-pink.min.css");
echo \Phalcon\Tag::javascriptInclude("https://code.getmdl.io/1.3.0/material.min.js");
echo \Phalcon\Tag::javascriptInclude("https://code.jquery.com/jquery-3.1.1.min.js");
echo \Phalcon\Tag::javascriptInclude("../phalcon/js/materialize.js");
echo \Phalcon\Tag::javascriptInclude("../phalcon/js/script.js");
echo \Phalcon\Tag::stylesheetLink("../phalcon/css/materialize.css");

?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<html ng-app lang="en">
<head>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=no">
    <body  material fluid>

    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title">ИАЦ</span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" href="">Link</a>
                    <a class="mdl-navigation__link" href="">Link</a>
                    <a class="mdl-navigation__link" href="">Link</a>
                    <a class="mdl-navigation__link" href="">Link</a>
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Меню</span>
            <nav class="mdl-navigation">
                <?php
                $menus = Menu::find(
                    [
                        "limit" => "5"
                    ]
                );
                foreach($menus as $menu){
                    echo  "<a  class='mdl-navigation__link'  href=./".$menu->getMenuNameTranslit().">".$menu->getMenuName()."</a>";
                }
                ?>
            </nav>
        </div>
        <main class="mdl-layout__content">
            <div class="page-content">

            <?php
               echo $this->getContent();
            ?>

            </div>
        </main>
    </div>



<?php //echo $this->getContent();?>
