<?php

// $this->assets->outputJs();
echo \Phalcon\Tag::stylesheetLink("../phalcon/css/style.css");
echo \Phalcon\Tag::stylesheetLink("https://fonts.googleapis.com/icon?family=Material+Icons");
echo \Phalcon\Tag::stylesheetLink("https://code.getmdl.io/1.3.0/material.indigo-pink.min.css");
echo \Phalcon\Tag::javascriptInclude("https://code.getmdl.io/1.3.0/material.min.js");
echo \Phalcon\Tag::javascriptInclude("https://code.jquery.com/jquery-3.1.1.min.js");
echo \Phalcon\Tag::javascriptInclude("../phalcon/js/materialize.js");
echo \Phalcon\Tag::javascriptInclude("../phalcon/js/script.js");
echo \Phalcon\Tag::stylesheetLink("../phalcon/css/materialize.css");

?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<html ng-app lang="en">
<head>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=no">
    <body  material fluid>

    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
        <header class="mdl-layout__header">
            <div class="mdl-layout__header-row">
                <!-- Title -->
                <span class="mdl-layout-title">
                    <?php
                    if(isset($getid)){
                        $mcontactName = Contact::findFirst($getid);
                        echo " | ".$mcontactName->getMcontactName();
                    }
                    ?>
                </span>
                <!-- Add spacer, to align navigation to the right -->
                <div class="mdl-layout-spacer"></div>
                <!-- Navigation. We hide it in small screens. -->
                <nav class="mdl-navigation mdl-layout--large-screen-only">
                    <a class="mdl-navigation__link" href="">Link</a>
                    <a class="mdl-navigation__link" href="">Link</a>
                    <a class="mdl-navigation__link" href="">Link</a>
                    <a class="mdl-navigation__link" href="">Link</a>
                </nav>
            </div>
        </header>
        <div class="mdl-layout__drawer">
            <span class="mdl-layout-title">Меню</span>
            <nav class="mdl-navigation">
                <?php
                $menus = Menu::find(
                    [
                        "limit" => "5"
                    ]
                );
                foreach($menus as $menu){
                    echo  "<a  class='mdl-navigation__link'  href=/phalcon/public/".$menu->getMenuNameTranslit().">".$menu->getMenuName()."</a>";
                }
                ?>
            </nav>
        </div>
        <main class="mdl-layout__content">
            <div class="page-content">

            <?php
               echo $this->getContent();
            ?>

<!--Красный кругляш для редактирования разделов -->
                <div class="fixed-action-btn horizontal click-to-toggle">
                    <a class="btn-floating btn-large red">
                        <i class="material-icons">menu</i>
                    </a>
                    <ul>
                        <li><a href="../<?php $_SERVER['REDIRECT_URL'] ?>editcontact" class="btn-floating red"><i class="material-icons">mode_edit</i></a></li>
                        <li><a class="btn-floating yellow darken-1"><i class="material-icons">format_quote</i></a></li>
                        <li><a class="btn-floating green"><i class="material-icons">publish</i></a></li>
                        <li><a class="btn-floating blue"><i class="material-icons">attach_file</i></a></li>
                    </ul>
                </div>
                <!--Красный кругляш для редактирования разделов -->
            </div>
        </main>
    </div>



<?php //echo $this->getContent();?>
